name: docs
on:
  push:
    branches:
       - main

jobs:
  eva_build_docs:
    name: Build eva documentation
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:

    # Setup Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    # Update conda
    - name: Update conda
      run: conda update -n base -c defaults conda

    # Install pip
    - name: Install pip
      run: conda install pip

    # Install cartopy
    - name: Install cartopy
      run: conda install -c conda-forge cartopy

    # Clone the eva-docs repository
    - name: Clone eva-docs repo
      uses: actions/checkout@v2
      with:        
        lfs: true

    # Clone the eva repository
    - name: Clone eva repo
      uses: actions/checkout@v2
      with:
        repository: JCSDA-internal/eva
        path: './eva'
        lfs: true

    # Install eva-docs
    - name: Upgrade pip
      run: $CONDA/bin/pip3 install --upgrade pip
    #- name: Install eva-docs and dependencies
    #  run: $CONDA/bin/pip3 install --use-deprecated=legacy-resolver -r requirements-github.txt --user .
    - name: Install Python dependencies for eva-docs
      uses: py-actions/py-dependency-install@v4
      with:
        path: "requirements-github.txt"
    - name: Put eva-docs in the path
      #run: echo "$HOME/.local/bin"
      run: echo $GITHUB_PATH

    # Clone eva repository
    # Install eva
    - name: Install eva and dependencies
      run: $CONDA/bin/pip3 install --use-deprecated=legacy-resolver -r requirements-github.txt --user ./eva/
    - name: Put eva in the path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    # Install ipykernel
    - name: Install ipykernel
      run: $CONDA/bin/pip3 install ipykernel

    # Generate rst files for jupyter notebooks
    - name: Generate rst
      run: nbsite generate-rst --org asewnath --project-name eva-docs --examples notebooks

    # Generate sphinx-api docs
    - name: Generate sphinx-api docs
      run: sphinx-apidoc -o doc/API/ ./eva/src

    # Fix API index.md to include sphinx-api docs
    - name: Fix API index.md
      run: python doc/api_setup.py

    # Build html files for documentation
    - name: Build docs
      run: nbsite build --what=html --output=builtdocs --org asewnath --project-name eva-docs

    # Deploy to gh-pages
    - name: Deploy main
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./builtdocs
        cname: asewnath.github.io/eva-docs
        force_orphan: true
